# Generated by Django 2.2.6 on 2019-10-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationAlermItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('maxTageName', models.CharField(db_column='maxTageName', max_length=100)),
                ('maxTageDesc', models.CharField(db_column='maxTageDesc', max_length=100)),
                ('maxTageValue', models.DecimalField(blank=True, db_column='maxTageValue', decimal_places=4, max_digits=18, null=True)),
                ('classic', models.CharField(blank=True, db_column='classic', max_length=50, null=True)),
                ('minTageName', models.CharField(db_column='minTageName', max_length=100)),
                ('minTageDesc', models.CharField(db_column='minTageDesc', max_length=100)),
                ('minTageValue', models.DecimalField(blank=True, db_column='minTageValue', decimal_places=4, max_digits=18, null=True)),
                ('deviationValuet', models.DecimalField(blank=True, db_column='deviationValuet', decimal_places=4, max_digits=18, null=True)),
                ('beginTime', models.DateTimeField(db_column='beginTime')),
                ('endTime', models.DateTimeField(db_column='endTime')),
                ('tiemDiff', models.DecimalField(blank=True, db_column='tiemDiff', decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'DeviationAlermItem',
            },
        ),
        migrations.CreateModel(
            name='OvertemperatureRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=300, null=True)),
                ('area', models.CharField(blank=True, db_column='area', max_length=50, null=True)),
                ('classic', models.CharField(blank=True, db_column='classic', max_length=50, null=True)),
                ('maxValue', models.DecimalField(blank=True, db_column='maxValue', decimal_places=4, max_digits=18, null=True)),
                ('thresholdValuet', models.DecimalField(blank=True, db_column='thresholdValuet', decimal_places=4, max_digits=18, null=True)),
                ('beginTime', models.DateTimeField(db_column='beginTime')),
                ('endTime', models.DateTimeField(db_column='endTime')),
                ('tiemDiff', models.DecimalField(blank=True, db_column='tiemDiff', decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'OverTemperature',
            },
        ),
    ]
